language: ruby
sudo: false
cache: bundler

branches:
  only: master

rvm:
  - 2.4
  - 2.5
  - 2.6

gemfile:
 - gemfiles/rails4.2.gemfile
 - gemfiles/rails5.0.gemfile
 - gemfiles/rails5.1.gemfile
 - gemfiles/rails5.2.gemfile

matrix:
  fast_finish: true

before_install: rm Gemfile.lock gemfiles/*.lock
script: bundle exec rake test
